# NOTE: This package requires "Enable internet access during builds" in COPR
# settings (cargo fetches crate dependencies during the build).

%global debug_package %{nil}

Name:           zellij
Version:        0.43.1
Release:        1%{?dist}
Summary:        A terminal workspace and multiplexer

License:        MIT
URL:            https://github.com/zellij-org/zellij
Source0:        %{url}/archive/v%{version}/%{name}-%{version}.tar.gz

BuildRequires:  cargo >= 1.84
BuildRequires:  rust >= 1.84
BuildRequires:  gcc
BuildRequires:  cmake
BuildRequires:  pkgconfig(openssl)

%description
Zellij is a terminal workspace and multiplexer with a layout and plugin system.
Its default plugins ship as prebuilt WebAssembly assets in the source tree, so
only the main binary is compiled here (no wasm toolchain required).

%prep
%autosetup -n %{name}-%{version}
# Build with the distro's stock rust/cargo. Drop the upstream channel/target pin
# so mock doesn't try to fetch a rustup toolchain or the wasm32 target — the
# default plugins are already bundled as prebuilt .wasm under zellij-utils/assets.
rm -f rust-toolchain.toml

%build
# Build is handled in %%install: `cargo install --path .` builds only the zellij
# binary crate (which embeds the prebuilt plugin assets), not the wasm plugin
# crates, so no wasm32 target is needed.

%install
RUSTFLAGS='-C strip=symbols' cargo install --locked --root=%{buildroot}%{_prefix} --path .

# Remove cargo bookkeeping created by `cargo install`
rm -f %{buildroot}%{_prefix}/.crates.toml
rm -f %{buildroot}%{_prefix}/.crates2.json

# Shell completions, generated by the freshly built binary
mkdir -p %{buildroot}%{_datadir}/bash-completion/completions
mkdir -p %{buildroot}%{_datadir}/zsh/site-functions
mkdir -p %{buildroot}%{_datadir}/fish/vendor_completions.d
%{buildroot}%{_bindir}/%{name} setup --generate-completion bash > %{buildroot}%{_datadir}/bash-completion/completions/%{name}
%{buildroot}%{_bindir}/%{name} setup --generate-completion zsh  > %{buildroot}%{_datadir}/zsh/site-functions/_%{name}
%{buildroot}%{_bindir}/%{name} setup --generate-completion fish > %{buildroot}%{_datadir}/fish/vendor_completions.d/%{name}.fish

%files
%license LICENSE.md
%doc README.md
%{_bindir}/%{name}
%{_datadir}/bash-completion/completions/%{name}
%{_datadir}/zsh/site-functions/_%{name}
%{_datadir}/fish/vendor_completions.d/%{name}.fish

%changelog
* Wed Jun 24 2026 Hypercube <hypercube@binarypie.dev> - 0.43.1-1
- Initial package for Hypercube
